"""empty message

Revision ID: be438e1cbbe0
Revises: 3bfe55bf9a46
Create Date: 2026-01-14 10:20:08.390361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be438e1cbbe0'
down_revision = '3bfe55bf9a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_message_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('messages_toMessage_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['to_message_id'], ['id'])
        batch_op.drop_column('toMessage_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toMessage_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_toMessage_id_fkey', 'user', ['toMessage_id'], ['id'])
        batch_op.drop_column('to_message_id')

    # ### end Alembic commands ###
